# Generated by Django 2.1.7 on 2019-04-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notelink', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_user',
            new_name='linkUser',
        ),
    ]
