# Generated by Django 2.1.7 on 2019-04-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notelink', '0002_auto_20190412_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_name',
            new_name='linkName',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_url',
            new_name='linkUrl',
        ),
    ]
