# Generated by Django 2.1.7 on 2019-04-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notelink', '0003_auto_20190412_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='linkName',
            new_name='link_name',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='linkUrl',
            new_name='link_url',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='linkUser',
            new_name='link_user',
        ),
    ]
