# Generated by Django 2.1.7 on 2019-04-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notelink', '0004_auto_20190412_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_name',
            new_name='linkName',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_url',
            new_name='linkUrl',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_user',
            new_name='linkUser',
        ),
    ]
