# Generated by Django 2.1.7 on 2019-04-14 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notelink', '0005_auto_20190413_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteTitle', models.CharField(max_length=200)),
                ('noteText', models.TextField()),
                ('noteTimestamp', models.DateTimeField(auto_now_add=True)),
                ('noteSlug', models.SlugField(max_length=250)),
                ('noteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
