# Generated by Django 2.1.7 on 2019-04-15 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notelink', '0006_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='noteTimestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
